#:schema node_modules/wrangler/config-schema.json
name = "smail"
compatibility_date = "2024-09-25"
main = "app/worker.ts"
assets = { directory = "./build/client" }

[observability]
enabled = true

[[kv_namespaces]]
binding = "KV"
id = "5d8c90f565344d538b4f9e151496c60e"

[[d1_databases]]
binding = "DB"
database_name = "smail"
database_id = "8c307e67-6ee6-40b2-a8c0-ee7cf063d2f7"
preview_database_id = "8c307e67-6ee6-40b2-a8c0-ee7cf063d2f7"
migrations_dir = "app/drizzle"

[vars]
COOKIE_SECRET = "COOKIE_SECRET"
DOMAIN = "r3y.email"
# PASSWORD = "password"
TURNSTILE_SITE_KEY="0x4AAAAAAAwiAp94ONfEqU0I"